ci: Add blunderbuss config
googleapis/langchain-google-alloydb-pg-python pull request #131
Opened 2024-05-17 21:51 UTC by duwenxin99

Add blunderbuss config to auto-assign issues.

2024-05-18 21:30 UTC, jackwotherspoon approved these changes

2024-05-18 21:30 UTC, jackwotherspoon commented on .github/blunderbuss.yml
> +  - renovate
nit: add newline at end of file
```suggestion
  - renovate
  
```

2024-05-20 16:17 UTC, averikitsch requested changes

2024-05-20 16:17 UTC, averikitsch commented on .github/blunderbuss.yml
> +  - renovate
Remove this section. We want these PRs to be auto-assigned.

2024-05-20 16:17 UTC, averikitsch commented on .github/blunderbuss.yml
> +assign_issues:
Add `assign_prs:` with the same GitHub team so we have both issues and PRs auto-assigned.

2024-05-20 20:38 UTC, averikitsch approved these changes

2024-05-20 20:41 UTC, merged