feat: allow non-uuid data types for vectorstore primary key
googleapis/langchain-google-alloydb-pg-python pull request #226
Opened 2024-09-10 05:17 UTC by dishaprakash

feat: allow non-uuid data types for vectorstore primary key

2024-09-12 11:09 UTC, vishwarajanand approved these changes
Lgtm

2024-09-12 19:39 UTC, averikitsch requested changes

2024-09-12 19:39 UTC, averikitsch commented on src/langchain_google_alloydb_pg/engine.py
> +        If id column data type is invalid, an UNDEFINED_OBJECT_ERROR is thrown.
nit: remove this note since it's listed in raises

2024-09-12 19:39 UTC, averikitsch commented on tests/test_engine.py
> +            assert row in expected
Can we add a tests to insert text or documents with ids?

2024-09-16 22:06 UTC, averikitsch approved these changes

2024-09-16 22:06 UTC, merged