feat: Made add_embeddings method public
googleapis/langchain-google-alloydb-pg-python pull request #228
Opened 2024-09-11 06:20 UTC by twishabansal

Tested Pinecone DB migration using this method: https://github.com/twishabansal/vector-store-experiments/blob/c6f264558c6dba38170000244dd85375a7e5c329/pinecone/app.py#L164

2024-09-11 22:29 UTC, averikitsch requested changes

2024-09-11 22:29 UTC, averikitsch commented on src/langchain_google_alloydb_pg/async_vectorstore.py
> +    async def aadd_embeddings(
Let's keep this private here since it is the pure implementation of the vector store that we don't expect users to use directly

2024-09-11 22:29 UTC, averikitsch commented on src/langchain_google_alloydb_pg/async_vectorstore.py
> +    def add_embeddings(
I do like how this makes it clear to the user this isn't support, but since it's not a part of the interface let's remove this change.

2024-09-12 10:44 UTC, vishwarajanand commented on tests/test_async_vectorstore.py
> +    #### Custom Vector Store  #####
Consider removing this line

2024-09-12 10:53 UTC, vishwarajanand commented on tests/test_async_vectorstore.py
> +        )
Also applicable for `tests/test_vectorstore::test_add_embeddings`

2024-09-13 18:21 UTC, averikitsch approved these changes

2024-09-16 05:03 UTC, merged