docs: Add ChromaDB migration code snippets
googleapis/langchain-google-alloydb-pg-python pull request #297
Opened 2024-12-30 11:45 UTC by dishaprakash

docs: Add ChromaDB migration code snippets

2025-01-07 23:32 UTC, averikitsch requested changes

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    from alloydb_snippets import get_embeddings_service
I like the deduplication, but these snippets should not be reliant on each other. Please just add that code here. The function wrapper may also not be needed

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    )
Same comment for this code

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    )
Region tags should not include functions we have made wrapping the langchain code.

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    # [START chromadb_get_vectorstore]
We should be consistent in our region tags. Even thought this is different from the get_client, It might be easier for the TW to have all the same region tags

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    # [START chromadb_alloydb_migration_get_alloydb_vectorstore]
We can simplify this region tag a bit to make it easier to use like chromadb_migration_alloydb_vectorstore

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +        # [START chromadb_alloydb_migration_insert_data_batch]
This should include the line above so users know where the variables are coming from

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/data/chromadb_data/8cf8bed7-024a-496b-aa94-5afb3bb120d2/data_level0.bin
I rather have the tests just set up a Chroma DB and add documents like in https://python.langchain.com/docs/integrations/vectorstores/chroma/ rather than maintaining these data files

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +EMBEDDING_MODEL_NAME = "textembedding-gecko@001"
In the original guide we use FakeEmbeddigns since we are actually needing to generate embeddings.

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +ALLOYDB_TABLE_NAME = "alloydb_table"
nit: 
```suggestion
ALLOYDB_TABLE_NAME = "chroma_data"
```

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +"""Migrate ChromaDBVectorStore to Langchain AlloyDBVectorStore.
```suggestion
"""Migrate Chroma to LangChain AlloyDBVectorStore.
```

2025-01-07 23:32 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +Given a chromadb collection, the following code fetches the data from chromadb
I believe the name is Chroma not chromadb. `chromadb` seems like the name of their client library

2025-01-09 08:39 UTC, vishwarajanand commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +EMBEDDING_MODEL_NAME = "textembedding-gecko@001"
We considered 2 options:
1. Use FakeEmbeddings and add a note to the doc
2. [less preferred due to use of vertex embedding APIs in tests] Add a comment in code snippet to change embedding model as desired

2025-01-09 08:41 UTC, vishwarajanand commented on samples/migrations/data/chromadb_data/8cf8bed7-024a-496b-aa94-5afb3bb120d2/data_level0.bin
This suggestion is to add a test setup function, which will take some time to implement, but doesn't block the PR to be tested by TW.

2025-01-09 08:47 UTC, vishwarajanand commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    # [START chromadb_get_vectorstore]
Also, change `chromadb_vector_store` to `chromadb_client`

2025-01-15 09:06 UTC, dishaprakash commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +EMBEDDING_MODEL_NAME = "textembedding-gecko@001"
Replaced with FakeEmbeddings

2025-01-15 22:46 UTC, averikitsch approved these changes

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +        overwrite_existing=True,
To be safe, we should think about not setting this to True

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    embeddings_service = FakeEmbeddings(size=chromadb_vector_size)
Let's add a note to the code on why we are using FakeEmbeddings, ie "The VectorStore interface requires an embedding service. This workflow does not generating new embeddings, therefore you can use the FakeEmbeddings class to avoid any costs."

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +CHROMADB_VECTOR_SIZE = 768
nit: can this be simplified to just VECTOR_SIZE?

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +CHROMADB_COLLECTION_NAME = "test_chroma"
Is this the example value that Chroma LangChain docs use?

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    print("ChromaDB vectorstore reference initiated.")
nit: we are using both "vector store" and "vectorstore". Either is fine, let's just be consistent.

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +DB_PWD = "YOUR_DATABASE_PASSWORD"
nit: typically we add example values like "my-project-id", "us-central1", "my-cluster", "postgres", etc.

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +EMBEDDING_MODEL_NAME = "textembedding-gecko@001"
I don't think this variable is needed any more

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    print("ChromaDB migration AlloyDBVectorStore table created.")
Is this a duplicated comment from line 128?

2025-01-15 22:46 UTC, averikitsch commented on samples/migrations/chromadb_migration_test.py
> +    uuids = [f"{str(uuid.uuid4())}" for i in range(100)]
nit: can we bump this to 1000?

2025-01-18 00:11 UTC, vishwarajanand commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +    print("ChromaDB migration AlloyDBVectorStore table created.")
Rearranged the prints and tags

2025-01-18 00:12 UTC, vishwarajanand commented on samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
> +        overwrite_existing=True,
removed

2025-01-19 09:29 UTC, vishwarajanand approved these changes
LGTM

2025-01-19 09:40 UTC, merged