docs: Add Qdrant migration code snippets
googleapis/langchain-google-alloydb-pg-python pull request #298
Opened 2024-12-30 11:48 UTC by dishaprakash

docs: Add Qdrant migration code snippets

2025-01-07 23:34 UTC, averikitsch commented on samples/migrations/migrate_qrant_vectorstore_to_alloydb.py
> +"""Migrate QdrantVectorStore to Langchain AlloyDBVectorStore.
Please use the vector store class name

2025-01-07 23:34 UTC, averikitsch requested changes
See comments from Chroma PR

2025-01-07 23:37 UTC, averikitsch commented on samples/migrations/migrate_qrant_vectorstore_to_alloydb.py
> +            offset=offset,
nit: just add None here

2025-01-07 23:43 UTC, averikitsch commented on samples/migrations/qdrant_migration_test.py
> +DEFAULT_TABLE = "test_qdrant_migration" + str(uuid.uuid4())
We could use the local in memory to tests against https://python.langchain.com/docs/integrations/vectorstores/qdrant/#local-mode

2025-01-15 09:41 UTC, vishwarajanand commented on samples/migrations/qdrant_migration_test.py
> +    client.delete_collection(
Remove this or Add a note suggesting delete only helps avoid pre-existing collections

2025-01-15 09:43 UTC, vishwarajanand commented on samples/migrations/migrate_qdrant_vectorstore_to_alloydb.py
> +                pending, return_when=asyncio.FIRST_COMPLETED
Check whether it should be `ALL_COMPLETED` instead?

2025-01-15 22:49 UTC, averikitsch commented on samples/migrations/migrate_qdrant_vectorstore_to_alloydb.py
> +                pending, return_when=asyncio.FIRST_COMPLETED
FIRST_COMPLETED is correct, as soon as the first one is finished processing we can start processing more

2025-01-15 22:53 UTC, averikitsch approved these changes
Please see any comments from Chroma PR

2025-01-19 09:29 UTC, vishwarajanand approved these changes
LGTM

2025-01-19 09:40 UTC, merged